---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.projectName }}-pvc
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
